--------------------------------------------------------
--  DDL for DB Link GA_DEV4_NETSMS_ABC.NET
--------------------------------------------------------

  CREATE DATABASE LINK "GA_DEV4_NETSMS_ABC.NET"
   CONNECT TO "CORE" IDENTIFIED BY VALUES '05A3A50E8E009F2B9D7363883ACF50C82F755D79ECF73D9CDC'
   USING '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=5.17.8.14)(PORT=1523)))(CONNECT_DATA=(SID=DDABC13F)(SERVER=DEDICATED)))';
