--------------------------------------------------------
--  DDL for DB Link GA_PROD_NETSMS_BH.NET
--------------------------------------------------------

  CREATE DATABASE LINK "GA_PROD_NETSMS_BH.NET"
   CONNECT TO "NETDBA" IDENTIFIED BY VALUES '0543854DCD5A91E9BFB528D3E8A2D8AE2D99A1DD8C2B24F2BD'
   USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=5.16.8.190)(PORT=1521))(CONNECT_DATA=(SID=bhpr)))';
