--------------------------------------------------------
--  DDL for DB Link GA_SIT7_NETSMS_CTV.NET
--------------------------------------------------------

  CREATE DATABASE LINK "GA_SIT7_NETSMS_CTV.NET"
   CONNECT TO "CORE" IDENTIFIED BY VALUES '05BB712DBDD60844E21479576168A81ED1B47BDC9FFD8C9F09'
   USING '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=RACNET-CLTFT01.dcing.corp)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=dbri1ctv)))';
