--------------------------------------------------------
--  DDL for DB Link GA_SIT5_NETSMS_SOC.NET
--------------------------------------------------------

  CREATE DATABASE LINK "GA_SIT5_NETSMS_SOC.NET"
   CONNECT TO "CORE" IDENTIFIED BY VALUES '056CCED8F5FFD11616CAEDB18597E1E4BF532B8E0EA0A8957F'
   USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=5.17.8.208)(PORT=1523))(CONNECT_DATA=(SID=BIGT)))';
