--------------------------------------------------------
--  DDL for DB Link GA_SIT7_NETSMS_SOC.NET
--------------------------------------------------------

  CREATE DATABASE LINK "GA_SIT7_NETSMS_SOC.NET"
   CONNECT TO "CORE" IDENTIFIED BY VALUES '05D16E2557ECBC0644E658FB203B236C3FD4DF5E6EB1041AA0'
   USING '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=RACNET-CLTFT01.dcing.corp)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=SOCSAMX1)))';
