--------------------------------------------------------
--  DDL for DB Link GA_SIT4_NETSMS_BH.NET
--------------------------------------------------------

  CREATE DATABASE LINK "GA_SIT4_NETSMS_BH.NET"
   CONNECT TO "CORE" IDENTIFIED BY VALUES '05DC57CE0CC8246FE5253BED1CA6B3C48A3DFD076FCF6EFD1D'
   USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=5.17.8.208)(PORT=1523))(CONNECT_DATA=(SID=TIBHPV1)))';
