--------------------------------------------------------
--  DDL for DB Link GA_UAT_NETSMS_CTV.NET
--------------------------------------------------------

  CREATE DATABASE LINK "GA_UAT_NETSMS_CTV.NET"
   CONNECT TO "CORE" IDENTIFIED BY VALUES '057ED2EFAC31EB3E33639E7BA5AADA054D0814D415D808A54A'
   USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.28.20.78)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=UATCTV)))';
